### ISSUE TITLE
Local development setup

### ISSUE THREAD

**Issue by Mistobaan** [teticio/openai-proxy#2]
I really like the idea of this project. 

What changes would be required to be able to run it on a google colab and have the cache write to google drive files?

```
import openai_proxy
import openai

openai_proxy.monkeypatch_colab(openai, 'project-A', env='dev', cache="/content/drive/MyDrive/.openai-proxy-cache")
openai.chat.complete.create(...)

openai_proxy.get_statistics('project-A')
```

**Comment by teticio** [comment]
Hi there. Thanks for the feedback. Can you give me a use case for this? If you don't need the proxying, then a simple pass through with local caching (and writing out to disk) could be done fairly easily adapting the code in `proxy0.py` and `proxy1.py`. In the end it would be a different project though, I think.

**Comment by Mistobaan** [comment]
Yes you are right. I realized that to be really effective across units it has to be deployed to one location. 
How much it costs (ball-park) to keep the system deployed on AWS?  ~$5 /month?

**Comment by teticio** [comment]
Well as it stands it is practically free as it just uses dynamodb and lambda functions. For a heavy use of OpenAI you'd have to estimate the cost on AWS, but it would be a fraction of the OpenAI cost.
